### PR TITLE
Feat: add tests

### PR DESCRIPTION
**Pull request by henry-lp**
More test cases (#1)

### CODE REVIEW

**Comment by henry-lp** [comment]
@monperrus Ready for review. I don't think Travis work unless it is set-up by repo owner :) . 

Perhaps we should merge and then you can activate this travis for this repo. WDYT ?

**Comment by monperrus** [comment]
Travis is already activated: https://travis-ci.com/github/repairnator/repairnator-integration-tests/builds/155894861

So we need to make this one green :-)

**Comment by henry-lp** [comment]
Right, I got confused by `https://travis-ci.com`  instead of .org  .

**Comment by henry-lp** [comment]
Ready for merge :)

**Comment by monperrus** [comment]
Thanks a lot Henry!

**Pull request merged**
